---
- hosts: all
  become: true
  vars:
    kubernetes_allow_pods_on_master: true
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes

  pre_tasks:
    - name: Update packages
      dnf:
        name: '*'
        state: latest

    - name: autoremove
      dnf:
        autoremove: yes

  post_tasks:
    - name: Reboot
      reboot:
        reboot_timeout: 120
